name: Auto approve

on:
  workflow_dispatch:
    inputs:
      pullRequestNumber:
        description: Pull request number to auto-approve
        required: true
      reason:
        description: Reason for auto-approval
        required: false

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
    steps:
    - name: Auto Approve
      uses: hmarr/auto-approve-action@v3
      with:
        pull-request-number: ${{ github.event.inputs.pullRequestNumber }}
        review-message: "Auto approved"

    - name: Add a label
      id: add_a_label
      uses: studroid/label-pr-or-issue-action@v1
      with:
        pr-or-issue-number: ${{ github.event.inputs.pullRequestNumber }}
        label: "auto-approved"

    - name: Send Slack Message
      id: slack
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
          {
            "pull_request_title": "${{ steps.add_a_label.outputs.pr_or_issue_title }}",
            "pull_request_url": "${{ steps.add_a_label.outputs.pr_or_issue_url }}",
            "reason": "${{ github.event.inputs.reason }}"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
