name: Auto approve
on:
  pull_request:
    types: [ labeled ]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: contains(github.event.pull_request.labels.*.name, 'auto-approve')
    steps:
      - uses: hmarr/auto-approve-action@v3
