name: Auto approve

on:
  workflow_dispatch:
    inputs:
      pullRequestNumber:
        description: Pull request number to auto-approve
        required: true
      reason:
        description: Reason for auto-approval
        required: false

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - name: Auto Approve
      uses: hmarr/auto-approve-action@v3
      with:
        pull-request-number: ${{ github.event.inputs.pullRequestNumber }}
        review-message: "Auto approved"

    - name: Send Slack Message
      id: slack
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
          {
            "pull_request_title": "${{ github.event.pull_request.title }}",
            "pull_request_url": "${{ github.event.pull_request.html_url }}",
            "pull_request_statuses_url": "${{ github.event.pull_request.statues_url }}"
            "reason": "${{ github.event.inputs.reason }}"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
