# This is a basic workflow to help you get started with Actions

name: Pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow if Manual workflow gets completed
  workflow_run:
    workflows: ["Manual workflow", "Labeler"]
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "pipeline"
  pipeline:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # Continue only if Manual workflow was successful
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
    
      - name: Show branch ref
        run: echo "${{toJson(github.ref)}}"
        
      - name: Show github context
        run: echo "${{toJson(github)}}"
