name: Print branch name

on:
  workflow_dispatch:

jobs:
  branch-name:
    runs-on: ubuntu-latest
    steps:
    - name: Echo branch name
      run: echo "${{ github.ref_name }}"

    - name: Set output
      id: vars
      run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
    - name: Check output
      run: echo ${{ steps.vars.outputs.short_ref }}
    
    - name: Another way
      run: |
        echo "BRANCH_NAME=${GITHUB_REF##*/}"
